### ISSUE TITLE
Can't find output on first build

### ISSUE THREAD

**Issue by 3x071c** [hyrious/esbuild-dev#22]
When running `esbuild-dev` for the first time (without an existing `node_modules/.esbuild-dev` directory), it fails to find the output:
```console
> esbuild-dev --watch --bundle --platform=node --target=node19 --packages=external --define:DEBUG=true --sourcemap src/index.ts

node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module '.../node_modules/.esbuild-dev/src+index.ts.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.8.1
[esbuild-dev] child process stopped with code 1
```

It does execute the current build on subsequent runs. To clarify: All files exist as they should when I check after the first run, it appears that there's a race condition where the output is called before the files are written to the file system.

**Comment by hyrious** [comment]
Thank you for reporting this. I haven't seen this before but I may know what's the culprit: when `esbuild.watch()` finishes the first build has not been done.

I will fix this issue in the next patch version.
